# Change these first
owner: demonsteru # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Libreddit
    url: https://lr.eka.monster
 # - name: YTMous
  #  url: https://ytmous.eka.monster
  - name: Hastebin
    url: https://haste.eka.monster
  - name: PrivateBin
    url: https://bin.eka.monster
  - name: StatPing
    url: https://stat.eka.monster
  - name: LibreX
    url: https://librex.eka.monster  
  - name: SearxNG
    url: https://sx.eka.monster 
  - name: SearxNG II
    url: https://sng.eka.monster 
  - name: SearxNG III
    url: https://sx3.eka.monster
  - name: Whoogle Poko
    url: https://wg.poko.dob.jp
  - name: SearxNG Poko
    url: https://sx.poko.dob.jp

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.eka.monster
  # baseUrl: /up
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage:  Status Page for Eka.Monster Services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
